### ISSUE TITLE
Example doesn't work?

### ISSUE THREAD

**Issue by nhouse** [posabsolute/jQuery-printPage-plugin#14]
I'm sure I'm missing something here, but when I download this repository and open index.html, the print functionality doesn't work in IE, Chrome, or FF. When the links are clicked new windows open.

The consoles show these errors:

Chrome says:

Uncaught TypeError: Object #<Object> has no method 'on' 

jquery.printPage.js:20

Firefox says:

TypeError: this.on is not a function

jquery...Page.js (line 20)

Do I need to modify your example file in order for it to work?

Thank you.

**Comment by myrage18** [comment]
Used to be a great plugin... it's now refusing to work... I tried a lot of different jQuery versions... The master pack give error at first with jQuery 1.4.4 included:this.on is not a function

Then if we update jQuery to a more recent version like 1.12.3, 1.11.1 this error message is gone, but there's a new one: 
`ReferenceError: _this is not defined`
`_this.settings.id = (pluginOptions.id) ? pluginOptions.id : $(el).attr('id');`

This plugin was doing such a perfect job, would have to check for a different one to replace it... unless it's something we can easily fix ?

**Comment by llcool** [comment]
Have a look at the demo page: http://www.position-absolute.com/creation/print/
You will see jquery.printPage.js does not contain _this and it works, but you will need to have href set.

**Comment by myrage18** [comment]
Great thanks a lot... It's working. I also successfully managed to have a old version working by changing only the .live() with .on(). I am using a print.php file in my project to handle all the "print" functions and this work perfectly for my needs :)
