### ISSUE TITLE
Not fitting page IE

### ISSUE THREAD

**Issue by ViezeVingertjes** [posabsolute/jQuery-printPage-plugin#25]
Hi,

I am trying to use the plugin, and it works great in Chrome.
In IE on the other hand, i used the width/height fix for the iFrame to get it printed at all, but now when printing through the button, it will cut the page off. When i print it manually while being on the page itself, it prints correct.

Anyone has a clue why this happens?

**Comment by brammittendorff** [comment]
This is your solution:
https://github.com/brammittendorff/jQuery-printPage-plugin
