### ISSUE TITLE
IE 11 throwing 404 on Print URL

### ISSUE THREAD

**Issue by chillmi** [posabsolute/jQuery-printPage-plugin#36]
Something in our environment on **some** workstations is causing IE 11 to throw a 404 when trying to print a page generated using a particular URL.

Using Fiddler, I can see that the print URL is being re-written as a series of 8 random characters + .htm when using IE 11 on the affected workstations.

Using FireFox on the same workstation does not present the issue and the page is printed as required.  

Any ideas how to resolve this issue with IE 11?

**Comment by point-nine** [comment]
We have encountered the same error today using IE 11.  Works fine in Chrome, but get 404 when trying to print from IE 11.

**Comment by chillmi** [comment]
We have determined the issue was caused by a Windows Update (KB4021558 and related).  Microsoft has released a patch:  KB4032782.  The patch appears to fix the issue.  Hope this helps!

**Comment by point-nine** [comment]
It helps a lot ... thanks!
